cloud:
  aws:
    region:
      static: us-west-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA5LWLQ3IV5RE6L5B2
      secret-key: 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
    end-point:
      uri: https://sqs.us-west-1.amazonaws.com/918476085803/Webhook_Receiver
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
      