cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    stack:
      auto: false
    credentials:
      access-key: AKIA3U6TDFVC2EDOZUUN
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/800917237061/webhook_receiver
logging:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error
      